language: php

cache:
  directories:
    $HOME/.composer/cache/files

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpspec run --no-interaction
